//
//  ProjectCloseColors.swift
//  ProjectClose
//
//  Created by raj on 03/01/17.
//  Copyright © 2017 diskodev. All rights reserved.
//

class ProjectCloseColors {
    static let welcomeViewControllerImageOverlayBackgroundColor = "FFFFFF"
    static let welcomeViewControllerLogoTitleColor = "2C3541"
    static let welcomeViewControllerLogoBorderColor = "2C3541"
    static let welcomeViewControllerHustleTitleColor = "47BB7F"
    static let welcomeViewControllerCloseMoreTitleColor = "47BB7F"
    static let welcomeViewControllerSalesTitleColor = "47BB7F"
    static let welcomeViewControllerRegisterViewColor = "47BB7F"
    static let welcomeViewControllerLoginViewColor = "47BB7F"
    static let welcomeViewControllerNewUserTitleColor = "FFFFFF"
    static let welcomeViewControllerExistingUserTitleColor = "FFFFFF"
    static let welcomeViewControllerRegisterTitleColor = "FFFFFF"
    static let welcomeViewControllerLoginTitleColor = "FFFFFF"
    static let welcomeViewControllerWebsiteTitleColor = "2C3541"
    static let welcomeViewControllerHelpTitleColor = "2C3541"
    static let welcomeViewControllerSeperatorViewColor = "FFFFFF"
    static let welcomeViewControllerOrTitleColor = "47BB7F"
    static let welcomeViewControllerOrBackgroundColor = "FFFFFF"

    static let loginViewControllerImageOverlayBackgroundColor1 = "000C40"
    static let loginViewControllerImageOverlayBackgroundColor2 = "E0EAFC"
    static let loginViewControllerImageOverlayBackgroundColor = "FFFFFF"
    static let loginViewControllerLogoTitleColor = "FFFFFF"
    static let loginViewControllerDescriptionTitleColor = "FFFFFF"
    static let loginViewControllerLogoBorderColor = "2C3541"
    static let loginViewControllerTextFieldTintColor = "47BB7F"
    static let loginViewControllerEmailTextFieldColor = "47BB7F"
    static let loginViewControllerEmailTextFieldPlaceholderColor = "2C3541"
    static let loginViewControllerPasswordTextFieldColor = "47BB7F"
    static let loginViewControllerPasswordTextFieldPlaceholderColor = "2C3541"
    static let loginViewControllerEmailTextFieldBackgroundColor = "FFFFFF"
    static let loginViewControllerPasswordTextFieldBackgroundColor = "FFFFFF"
    static let loginViewControllerLoginButtonTitleColor = "FFFFFF"
    static let loginViewControllerLoginButtonBackgroundColor = "47BB7F"
    static let loginViewControllerForgotPasswordButtonTitleColor = "2C3541"
    static let loginViewControllerSignupButtonTitleColor = "2C3541"
    static let loginViewControllerHelpButtonTitleColor = "2C3541"

    static let allViewControllersNavigationBarBackgroundColor = "2C3541"
    static let allViewControllersNavigationBarTitleColor = "FFFFFF"
    static let allViewControllersTabBarBackgroundColor = "2C3541"
    static let allViewControllersTabBarSelectedTitleColor = "47BB7F"
    static let allViewControllersTabBarUnSelectedTitleColor = "FFFFFF"
    static let allViewControllersTabBarSelectedTintColor = "47BB7F"

    static let pagingInboxViewControllerPageMenuTitleColor = "2C3541"
    static let pagingInboxViewControllerSelectedPageMenuTitleColor = "47BB7F"
    static let pagingInboxViewControllerSelectedPageMenuUnderlineColor = "47BB7F"
    static let pagingInboxViewControllerAddTaskButtonColor = "FFFFFF"

    static let opportunitiesViewControllerAddLeadButtonColor = "FFFFFF"

    static let leadDetailsPagingMenuTitleColor = "2C3541"
    static let leadDetailsPagingMenuSelectedTitleColor = "47BB7F"
    static let leadDetailsPagingMenuUnderlineColor = "47BB7F"

    static let leadsTableViewControllerAddLeadButtonColor = "FFFFFF"

    static let addLeadViewControllerTextFieldTintColor = "47BB7F"
    static let addLeadViewControllerCompanyNameTitleColor = "2C3541"
    static let addLeadViewControllerCompanyNameTextFieldTitleColor = "47BB7F"
    static let addLeadViewControllerCompanyDescriptionTitleColor = "2C3541"
    static let addLeadViewControllerCompanyDescriptionTextFieldTitleColor = "47BB7F"
    static let addLeadViewControllerCompanyAddressTitleColor = "2C3541"
    static let addLeadViewControllerCompanyAddressTextFieldTitleColor = "47BB7F"
    static let addLeadViewControllerAddLeadButtonBackgroundColor = "47BB7F"
    static let addLeadViewControllerAddLeadButtonTitleColor = "FFFFFF"

    static let addLeadOpportunityViewControllerTextFieldTintColor = "47BB7F"
    static let addLeadOpportunityViewControllerDescriptionTitleColor = "2C3541"
    static let addLeadOpportunityViewControllerDescriptionTextFieldTitleColor = "47BB7F"
    static let addLeadOpportunityViewControllerExpiryDateTitleColor = "2C3541"
    static let addLeadOpportunityViewControllerExpiryDateTextFieldTitleColor = "47BB7F"
    static let addLeadOpportunityViewControllerValueTitleColor = "2C3541"
    static let addLeadOpportunityViewControllerValueTextFieldTitleColor = "47BB7F"
    static let addLeadOpportunityViewControllerConfidenceTitleColor = "2C3541"
    static let addLeadOpportunityViewControllerConfidenceTextFieldTitleColor = "47BB7F"
    static let addLeadOpportunityViewControllerAssignedToTitleColor = "2C3541"
    static let addLeadOpportunityViewControllerAssignedToValueTitleColor = "47BB7F"
    static let addLeadOpportunityViewControllerAddLeadOpportunityButtonBackgroundColor = "47BB7F"
    static let addLeadOpportunityViewControllerAddLeadOpportunityButtonTitleColor = "FFFFFF"

    static let addOpportunityViewControllerTextFieldTintColor = "47BB7F"
    static let addOpportunityViewControllerDescriptionTitleColor = "2C3541"
    static let addOpportunityViewControllerDescriptionTextFieldTitleColor = "47BB7F"
    static let addOpportunityViewControllerExpiryDateTitleColor = "2C3541"
    static let addOpportunityViewControllerExpiryDateTextFieldTitleColor = "47BB7F"
    static let addOpportunityViewControllerLeadLabelTitleColor = "2C3541"
    static let addOpportunityViewControllerLeadValueTitleColor = "47BB7F"
    static let addOpportunityViewControllerValueTitleColor = "2C3541"
    static let addOpportunityViewControllerValueTextFieldTitleColor = "47BB7F"
    static let addOpportunityViewControllerConfidenceTitleColor = "2C3541"
    static let addOpportunityViewControllerConfidenceTextFieldTitleColor = "47BB7F"
    static let addOpportunityViewControllerAssignedToLabelTitleColor = "2C3541"
    static let addOpportunityViewControllerAssignedToValueTitleColor = "47BB7F"
    static let addOpportunityViewControllerAddOpportunityButtonBackgroundColor = "47BB7F"
    static let addOpportunityViewControllerAddOpportunityButtonTitleColor = "FFFFFF"

    static let addLeadTasksViewControllerTextFieldTintColor = "47BB7F"
    static let addLeadTasksViewControllerTaskDescriptionTitleColor = "2C3541"
    static let addLeadTasksViewControllerTaskDescriptionTextFieldTitleColor = "47BB7F"
    static let addLeadTasksViewControllerAssignedToLabelTitleColor = "2C3541"
    static let addLeadTasksViewControllerAssignedToValueTitleColor = "47BB7F"
    static let addLeadTasksViewControllerAssignedToTextFieldTitleColor = "47BB7F"
    static let addLeadTasksViewControllerLeadLabelTitleColor = "2C3541"
    static let addLeadTasksViewControllerLeadValueTitleColor = "47BB7F"
    static let addLeadTasksViewControllerExpiryDateTitleColor = "2C3541"
    static let addLeadTasksViewControllerExpiryDateTextFieldTitleColor = "47BB7F"
    static let addLeadTasksViewControllerAddLeadTaskButtonBackgroundColor = "47BB7F"
    static let addLeadTasksViewControllerAddLeadTaskButtonTitleColor = "FFFFFF"

    static let addLeadContactViewControllerTextFieldTintColor = "47BB7F"
    static let addLeadContactViewControllerNameTitleColor = "2C3541"
    static let addLeadContactViewControllerNameTextFieldTitleColor = "47BB7F"
    static let addLeadContactViewControllerEmailTitleColor = "2C3541"
    static let addLeadContactViewControllerEmailTextFieldTitleColor = "47BB7F"
    static let addLeadContactViewControllerPhoneTitleColor = "2C3541"
    static let addLeadContactViewControllerPhoneTextFieldTitleColor = "47BB7F"
    static let addLeadContactViewControllerAddLeadContactButtonBackgroundColor = "47BB7F"
    static let addLeadContactViewControllerAddLeadContactButtonTitleColor = "FFFFFF"

    static let settingsTableViewControllerProfileImageBorderColor = "2C3541"
    static let settingsTableViewControllerNameTitleColor = "2C3541"
    static let settingsTableViewControllerEmailTitleColor = "2C3541"
    static let settingsTableViewControllerHeaderBackgroundColor = "2C3541"
    static let settingsTableViewControllerHeaderTitleColor = "FFFFFF"
    static let settingsTableViewControllerContentColor = "47BB7F"
    static let settingsTableViewControllerLogoutButtonBackgroundColor = "47BB7F"
    static let settingsTableViewControllerLogoutButtonTitleColor = "FFFFFF"

    static let settingsViewControllerProfileImageBorderColor = "2C3541"
    static let settingsViewControllerNameTitleColor = "2C3541"
    static let settingsViewControllerEmailTitleColor = "2C3541"
    static let settingsViewControllerYourSettingsLabelBackgroundColor = "2C3541"
    static let settingsViewControllerOrgSettingsLabelBackgroundColor = "2C3541"
    static let settingsViewControllerYourSettingsLabelTitleColor = "FFFFFF"
    static let settingsViewControllerOrgSettingsLabelTitleColor = "FFFFFF"
    static let settingsViewControllerYourProfileSettingsButtonTitleColor = "47BB7F"
    static let settingsViewControllerYourAudioSettingsButtonTitleColor = "47BB7F"
    static let settingsViewControllerOrgUsersSettingsButtonTitleColor = "47BB7F"

    static let settingsViewControllerLogoutButtonBackgroundColor = "47BB7F"
    static let settingsViewControllerLogoutButtonTitleColor = "FFFFFF"

    static let addUserViewControllerTextFieldTintColor = "47BB7F"
    static let addUserViewControllerNameLabelTitleColor = "2C3541"
    static let addUserViewControllerNameTextFieldTitleColor = "47BB7F"
    static let addUserViewControllerNameTextFieldPlaceholderColor = "2C3541"
    static let addUserViewControllerEmailLabelTitleColor = "2C3541"
    static let addUserViewControllerEmailTextFieldTitleColor = "47BB7F"
    static let addUserViewControllerEmailTextFieldPlaceholderColor = "2C3541"
    static let addUserViewControllerAddUserButtonTitleColor = "FFFFFF"
    static let addUserViewControllerAddUserButtonBackgroundColor = "47BB7F"

    static let usersTableViewControllerNameColor = "2C3541"
    static let usersTableViewControllerEmailColor = "47BB7F"

    static let chooseLeadsTableViewControllerCompanyNameColor = "2C3541"
    static let chooseLeadsTableViewControllerCompanyDescriptionColor = "47BB7F"

    static let leadsTableViewControllerCompanyNameColor = "2C3541"
    static let leadsTableViewControllerStatusColor = "47BB7F"

    static let leadOpportunityTableViewControllerValueColor = "2C3541"
    static let leadOpportunityTableViewControllerAssignedToColor = "2C3541"
    static let leadOpportunityTableViewControllerClosedStatusColor = "FF0000"
    static let leadOpportunityTableViewControllerPausedStatusColor = "2C3541"
    static let leadOpportunityTableViewControllerStatusColor = "47BB7F"
    static let leadOpportunityTableViewControllerActiveButtonColor = "47BB7F"
    static let leadOpportunityTableViewControllerPauseButtonColor = "2C3541"
    static let leadOpportunityTableViewControllerClosedButtonColor = "FF0000"
    static let leadOpportunityTableViewControllerPercentageColor = "47BB7F"

    static let leadTasksTableViewControllerTitleColor = "2C3541"
    static let leadTasksTableViewControllerSubtitleColor = "47BB7F"
    static let leadTasksTableViewControllerExpiredSubtitleColor = "FF0000"
    static let leadTasksTableViewControllerTableCellDeleteButtonColor = "FF0000"
    static let leadTasksTableViewControllerTableCellCloseButtonColor = "47BB7F"
    static let leadTasksTableViewControllerTableCellReOpenButtonColor = "47BB7F"
    static let leadTasksTableViewControllerTableCellTitleStrikeThroughColor = "2C3541"
    static let leadTasksTableViewControllerTableCellSubtitleStrikeThroughColor = "47BB7F"

    static let leadContactsTableViewControllerTitleColor = "2C3541"
    static let leadContactsTableViewControllerSubtitleColor = "47BB7F"
    static let leadContactsTableViewControllerTableCellDeleteButtonColor = "FF0000"
    static let leadContactsTableViewControllerTableViewCellContactOptionsBackgroundViewColor = "47BB7F"
    static let leadContactsTableViewControllerCommsButtonBackgroundColor = "FFFFFF"
    static let leadContactsTableViewControllerCommsOptionsImageTintColor = "47BB7F"

    static let leadMessagesTableViewControllerTitleColor = "2C3541"
    static let leadMessagesTableViewControllerSubtitleColor = "47BB7F"
    static let leadMessagesTableViewControllerImageViewBackgroundColor = "47BB7F"
    static let leadMessagesTableViewControllerImageViewTintColor = "47BB7F"
    static let leadMessagesTableViewControllerCommsOptionsTintColor = "47BB7F"

    static let leadStatusTableViewControllerTitleColor = "2C3541"
    static let leadStatusTableViewControllerSelectedTitleColor = "47BB7F"
    static let leadStatusTableViewControllerTableViewCellTintColor = "47BB7F"

    static let opportunityTableViewCellLeadLabelBorderColor = "47BB7F"
    static let opportunityTableViewCellLeadLabelTitleColor = "47BB7F"
    static let opportunityTableViewCellValueColor = "2C3541"
    static let opportunityTableViewCellAssignedToColor = "2C3541"
    static let opportunityTableViewCellStatusColor = "47BB7F"
    static let opportunityTableViewCellClosedStatusColor = "FF0000"
    static let opportunityTableViewCellPercentageColor = "47BB7F"
    static let opportunityTableViewCellPercentageViewBorderColor = "47BB7F"
    static let opportunityTableViewCellChangeStatusButtonColor = "47BB7F"
    static let opportunityTableViewCellSetActiveButtonColor = "47BB7F"
    static let opportunityTableViewCellPauseButtonColor = "2C3541"
    static let opportunityTableViewCellCloseButtonColor = "FF0000"

    static let inboxTasksTableViewCellLeadLabelBorderColor = "47BB7F"
    static let inboxTasksTableViewCellLeadLabelTitleColor = "47BB7F"
    static let inboxTasksTableViewControllerTitleColor = "2C3541"
    static let inboxTasksTableViewControllerSubtitleColor = "47BB7F"
    static let inboxTasksTableViewControllerExpiredSubtitleColor = "FF0000"
    static let inboxTasksTableViewControllerTableCellDeleteButtonColor = "FF0000"
    static let inboxTasksTableViewControllerTableCellCloseButtonColor = "47BB7F"
    static let inboxTasksTableViewControllerTableCellReOpenButtonColor = "47BB7F"
    static let inboxTasksTableViewControllerTableCellTitleStrikeThroughColor = "2C3541"
    static let inboxTasksTableViewControllerTableCellSubtitleStrikeThroughColor = "47BB7F"

    static let userProfileTableViewCellLogoutButtonBorderColor = "47BB7F"
    static let userProfileTableViewCellMainLabelColor = "2C3541"
    static let userProfileTableViewCellSubTitleLabelColor = "2C3541"
    static let userProfileTableViewCellLogoutButtonColor = "FFFFFF"
    static let userProfileTableViewCellLogoutButtonBackgroundColor = "47BB7F"

    static let allInboxTableViewControllerLeadTitleColor = "47BB7F"
    static let allInboxTableViewControllerTitleColor = "2C3541"
    static let allInboxTableViewControllerSubtitleColor = "47BB7F"
    static let allInboxTableViewControllerExpiredSubtitleColor = "FF0000"
    static let allInboxTableViewControllerTableCellTitleStrikeThroughColor = "2C3541"
    static let allInboxTableViewControllerTableCellSubtitleStrikeThroughColor = "47BB7F"

    static let doneInboxTableViewControllerLeadTitleColor = "47BB7F"
    static let doneInboxTableViewControllerTitleColor = "2C3541"
    static let doneInboxTableViewControllerSubtitleColor = "47BB7F"
    static let doneInboxTableViewControllerExpiredSubtitleColor = "FF0000"
    static let doneInboxTableViewControllerTableCellTitleStrikeThroughColor = "2C3541"
    static let doneInboxTableViewControllerTableCellSubtitleStrikeThroughColor = "47BB7F"

    static let futureInboxTableViewControllerLeadTitleColor = "47BB7F"
    static let futureInboxTableViewControllerTitleColor = "2C3541"
    static let futureInboxTableViewControllerSubtitleColor = "47BB7F"
    static let futureInboxTableViewControllerExpiredSubtitleColor = "FF0000"
    static let futureInboxTableViewControllerTableCellTitleStrikeThroughColor = "2C3541"
    static let futureInboxTableViewControllerTableCellSubtitleStrikeThroughColor = "47BB7F"

    static let reportsTableViewControllerSectionBackgroundColor = "47BB7F"
    static let reportsTableViewControllerSectionLeadNameTitleColor = "FFFFFF"

    static let reportTableViewCellReportTitleColor = "47BB7F"
    static let reportTableViewCellLowTitleColor = "47BB7F"
    static let reportTableViewCellHighTitleColor = "47BB7F"
    static let reportTableViewCellMetricColor = "47BB7F"
    static let reportTableViewCellGraphColor = "47BB7F"
    static let reportTableViewCellPercentageTitleColor = "47BB7F"
    static let reportTableViewCellStarImageTintColor = "47BB7F"

    static let metricTableViewCellReportTitleColor = "47BB7F"
    static let metricTableViewCellLowTitleColor = "47BB7F"
    static let metricTableViewCellHighTitleColor = "47BB7F"
    static let metricTableViewCellMetricColor = "47BB7F"
    static let metricTableViewCellGraphColor = "47BB7F"
    static let metricTableViewCellPercentageTitleColor = "47BB7F"
    static let metricTableViewCellStarImageTintColor = "47BB7F"
    static let metricTableViewLeftMetricTitleColor = "47BB7F"
    static let metricTableViewRightMetricTitleColor = "47BB7F"
    static let metricTableViewTopBarTitleColor = "47BB7F"
    static let metricTableViewBottomBarTitleColor = "47BB7F"
    static let metricTableViewWeekTextColor = "47BB7F"

    static let allTableViewCellTintColor = "47BB7F"
}
